name: SnoopCompile

on:
  push:
    # TODO: remove this once we enable precompilations
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.4.0-rc1']
        julia-arch: [x64]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: Instantiate target package
        run: julia --project=@. -e 'using Pkg; Pkg.instantiate();'
      - name: Install SnoopCompile and test dependencies
        run: |
          julia -e '
          using Pkg
          Pkg.develop(PackageSpec(; path=pwd()))
          Pkg.add("SnoopCompile")
          using SnoopCompile
          SnoopCompile.addtestdep()'
      - name: Generating precompile files
        run: julia --project=@. deps/SnoopCompile/compile.jl
      - name: Running Benchmark
        run: julia --project=@. deps/SnoopCompile/benchmark.jl

      # https://github.com/marketplace/actions/create-pull-request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update precompile_Juno.jl file
          # committer: YOUR NAME <yourEmail@something.com> # Change `committer` to your name and your email.
          title: 'SnoopCompile: Update precompile_Juno.jl file'
          labels: SnoopCompile
          branch: create-pull-request/SnoopCompile
      - name: Check output environment variable
        run: echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
